### ISSUE TITLE
Anime popular 

### ISSUE THREAD

**Issue by Jairamalawi** [mihonapp/website#100]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

I like reading anime that's why I want to download this

### Other details

That's all

**Comment by Soitora** [comment]
Not website related, and neither is it app related.
