### ISSUE TITLE
download was pause

### ISSUE THREAD

**Issue by dafuge** [mihonapp/website#126]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

![Screenshot_2024-12-06-15-45-08-358_app mihon](https://github.com/user-attachments/assets/834cf8f9-7dc1-4a30-be7f-b4c8e5a4c78b)

### Expected behavior

I hope it is starting

### Actual behavior

it always was pause

**Comment by Soitora** [comment]
Wrong repo
