### ISSUE TITLE
Kitsu changed domains 

### ISSUE THREAD

**Issue by nobile01** [mihonapp/website#127]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

1. Attempt to enable Kitsu tracking
2. Put in credentials to sign in 

### Expected behavior

It should log in 

### Actual behavior

It times out 

### Other details

Kitsu changed their domain, instead of https://kitsu.io/ it is https://kitsu.app/

**Comment by Smol-Ame** [comment]
1. This repo is for the Mihon website, not the Mihon app.
2. Mihon already swapped out the Kitsu tracker link when they changed/lost it back then, make sure your app is up-to-date.

**Comment by nobile01** [comment]
> 1. This repo is for the Mihon website, not the Mihon app.

Oh, I apologise for this, I can close this ticket and look for the app repo instead. 

>     2. Mihon already swapped out the Kitsu tracker link when they changed/lost it back then, make sure your app is up-to-date.

App version: 0.17.1 (standard, 3a100c7, 9, 2024-12-06T17:14:05Z) I installed it a few hours ago from https://mihon.app/download/, it wasn't the beta version, but the stable release. Unless the website has an older version?

**Comment by nobile01** [comment]
Ticket requested to be closed
