### ISSUE TITLE
extension tab. extension cant be updated.

### ISSUE THREAD

**Issue by afat123** [mihonapp/website#17]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

pressing update all / update on each extension

### Expected behavior

should be updated after update all is pressed.

### Actual behavior

pressing update all / update each extension doesnt work. after "installing" pop up, it didnt instal the update.

**Comment by MajorTanya** [comment]
This is the repo for Mihon's website. You're in completely the wrong place for this.

**Comment by Soitora** [comment]
try using the correct repo
