### ISSUE TITLE
ikigai mangas no carga los capítulos 

### ISSUE THREAD

**Issue by BastiVader** [mihonapp/website#59]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

1- entro a fuentes 
2- entro a ikigai mangas
3- entro al manga/manwha elegido 
4- entro a un capitulo 
5- da error 404 
6- entro al sitio web y si esta en capitulo correctamente 

### Expected behavior

1- entro a fuentes 
2- entro a ikigai mangas
3- entro al manga/manwha elegido 
4- entro a un capitulo 
5- leo el capitulo 

### Actual behavior

1- entro a fuentes 
2- entro a ikigai mangas
3- entro al manga/manwha elegido 
4- entro a un capitulo 
5- da error 404 
6- entro al sitio web y si esta en capitulo correctamente 

### Other details

Tampoco  deja descargar el capitulo 

Link de la fuente https://ikigaimangas.com/

**Comment by Soitora** [comment]
1. This is not related to our website.
2. Mihon has no control over, or responsibility, over your sources, we do not offer any form of support for this.
