### ISSUE TITLE
Ikigai mangas no carga imágenes 

### ISSUE THREAD

**Issue by BastiVader** [mihonapp/website#61]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

Entro a la fuente 
Elijo el manga/manwha 
Entro al capítulo 
Aparece "No se encuentran páginas"
Entro a la web y si aparecen páginas 

### Expected behavior

Entro a la fuente 
Elijo el manga/manwha 
Entro al capítulo 
Aparece las páginas 

### Actual behavior

Entro a la fuente 
Elijo el manga/manwha 
Entro al capítulo 
Aparece "No se encuentran páginas"
Entro a la web y si aparecen las páginas 

### Other details

Al entrar a la web si puedo leer los capítulos y con todos los mangas/manhwas

**Comment by MajorTanya** [comment]
This is the repository for the Mihon website. Your complaint is an extension issue and should be filed with the maintainers of your extension repository, not with Mihon. Especially not in the website repository.

---

Traducción al español por Google:
Este es el repositorio del sitio web de Mihon.  Su queja es un problema de extensión y debe presentarse ante los encargados de su repositorio de extensiones, no ante Mihon.  Especialmente no en el repositorio del sitio web.
