### ISSUE TITLE
MY LIBRARY ISN'T UPDATING/ NO NOTIFICATION SHOWN

### ISSUE THREAD

**Issue by BlackScythe101** [mihonapp/website#64]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

When refreshing library there's no notification 
![Screenshot_20240511-085608](https://github.com/mihonapp/website/assets/169521709/e98bdfde-82ff-43b7-82c1-151264138e00)

### Expected behavior

It's the same as i installed the app the library isn't updating 
![Screenshot_20240511-085611](https://github.com/mihonapp/website/assets/169521709/a8198650-1915-4f98-8fe6-fd5f68412d5b)
![Screenshot_20240511-085613](https://github.com/mihonapp/website/assets/169521709/b504b19f-fc6a-4c3e-853d-dd63be08760c)

### Actual behavior

I tried looking for resolution but nothing worked

**Comment by AntsyLich** [comment]
Wrong repository.
