### ISSUE TITLE
Higher quality render of phone on homepage

### ISSUE THREAD

**Issue by TimoNotThy** [mihonapp/website#67]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

The [render of the phone with the app open](https://github.com/mihonapp/website/blob/main/website/src/public/home/phone.dark.webp) is not of high quality. Replacing it with a render that has a higher resolution would look better.

### Other details

![current picture](https://raw.githubusercontent.com/mihonapp/website/main/website/src/public/home/phone.dark.webp)

**Comment by Soitora** [comment]
Higher resolution renders exist, using a low resolution is to keep the front-page loading near-instantaneous even on bad internet.

**Comment by TimoNotThy** [comment]
I don't know a lot about web development but is it not possible to first load the low resolution image and then 'slowly' load the high resolution version after the site has loaded.

**Comment by prenaissance** [comment]
> I don't know a lot about web development but is it not possible to first load the low resolution image and then 'slowly' load the high resolution version after the site has loaded.

It is completely possible using events on the image element.

There's also an option, without JavaScript, for the browser to load the image best suited for the screen resolution using `srcset` https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by Soitora** [comment]
I just went ahead and used the higher quality renders instead.
Fixed by 915da5bd07095f4164a019d24878eb963b889eda
