### ISSUE TITLE
Ikigai cambio de dominio 

### ISSUE THREAD

**Issue by BastiVader** [mihonapp/website#68]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

Entra a Mihon
Entra a Ikigai 
Elige manga/manwha 
Entra al capítulo 
Aparece "No hay páginas" (en todos los manwha)
Entra a la web y dice "cambiamos de dominio"

### Expected behavior

Entra a Mihon
Entra a Ikigai 
Elige manga/manwha 
Entra al capítulo 
Leer el capítulo 

### Actual behavior

Entra a Mihon
Entra a Ikigai 
Elige manga/manwha 
Entra al capítulo 
Aparece "No hay páginas" (en todos los manwha)
Entra a la web y dice "cambiamos de dominio"

### Other details

Ikigaimangas.com paso a https://nocbro.xyz/

**Comment by MajorTanya** [comment]
1. This is the repository for Mihon's website
2. Mihon doesn't provide any extensions itself, go ask your repo maintainer (not Mihon)
3. Don't open the exact same request (#69) again just because you didn't get a response yet or something
