### ISSUE TITLE
Ikigai no carga las imágenes 

### ISSUE THREAD

**Issue by BastiVader** [mihonapp/website#69]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

Entro a mihon
Voy a fuentes 
Elijo ikigai 
Elijo el manga/manwha 
Entro al capítulo y aparece "no hay imágenes"
Entro a la web y si carga las imágenes 

### Expected behavior

Entro a mihon
Voy a fuentes 
Elijo ikigai 
Elijo el manga/manwha 
Entro al capítulo y lo leo

### Actual behavior

Entro a mihon
Voy a fuentes 
Elijo ikigai 
Elijo el manga/manwha 
Entro al capítulo y aparece "no hay imágenes"
Entro a la web y si carga las imágenes 

### Other details

Gracias por siempre corregir los errores

**Comment by Soitora** [comment]
Are you dumb or just dumb?
