### ISSUE TITLE
Maximum Backups Field Removed

### ISSUE THREAD

**Issue by Animeboynz** [mihonapp/website#85]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I might fill out all of the requested information in this form.

### Maximum Backup Field
|   | Dark | Light |
|---|---|---|
| Prev | ![automatic_backups dark](https://github.com/user-attachments/assets/a3e31279-78c4-4705-8a3c-dc5d7b03c952) | ![automatic_backups light](https://github.com/user-attachments/assets/8603c5ae-c5ec-4f13-b4e9-c918645cce0e) |
| New | ![fd](https://github.com/user-attachments/assets/120b8dd3-e931-4e53-b44c-d4383bd85092) | ![fl](https://github.com/user-attachments/assets/85e22965-beb3-4f8d-8af1-227376e68c21) |

### Backup Image (Less Important?)
|   | Dark | Light |
|---|---|---|
| Prev | ![backup dark](https://github.com/user-attachments/assets/685fd69e-5aed-48b8-88cf-42b6e77ae0eb) | ![backup light](https://github.com/user-attachments/assets/e658c6a5-4f59-4182-8687-48ca332a61f0) |
| New | ![main_dark](https://github.com/user-attachments/assets/b0ed2104-2a9a-4b4b-bba5-4511b07c9340) | ![main_light](https://github.com/user-attachments/assets/6ab89ce3-abea-4f76-9515-5058ccbada43) |

**Comment by Soitora** [comment]
Could your PR this with optimized webp images? Check the old ones for general size etc
